[package]
name = "threadpool"
version = "0.1.0"
authors = ["gasiortomasz <gasior.tt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
crossbeam-channel = "0.5"
ntest = "0.7"
